### ISSUE TITLE
Global highlighting rules

### ISSUE THREAD

**Issue by Swiftpaws** [tualatin/tailforwindows#186]
**Question**
Is it possible to add highlight rules which apply globally? (Every file) 

**Example**
Highlight debug, info, error, etc... in whatever color for every file with the .log extension or have a combo box to choose your highlighter - like in Notepad++.

**UseCase**
I am working with many (Terabytes 10-50mb each)) of independent log files and I would like to have all of them highlighted the same way (when I decide to open them)

**Comment by tualatin** [comment]
Sorry for the late answer, I will give it a try.
