### ISSUE TITLE
Command line parameters to open log file not working

### ISSUE THREAD

**Issue by fakaki** [tualatin/tailforwindows#202]
v.2.3.8382.x

Since I could not find any example or documentation of command line parameters I guessed from old 1.x versions to instantly open a log file in started tail mode like

T4W.exe path\to\file.log

But that's not working.

Is there any other parameter like -file I have to use?
 -> In the code I found that if none of the /arguments is supplied then any parameter is expected to be a a path\filename. Found this was introduced in commit 0045dcd in App.xaml.cs but either it is not working in latest version, maybe the RegEx does not match something like C:\test\file.log

Is it possible to open more than one file from command line and open those in tabs each?
Is Tail mode automatically started?

Thanks in advance!

**Comment by tualatin** [comment]
Fixed in Test branch

**Comment by tualatin** [comment]
@fakaki take a look #204
