### ISSUE TITLE
[SOLVED] Windows Defender SmartScreen flags T4W.exe as unknown software

### ISSUE THREAD

**Issue by fakaki** [tualatin/tailforwindows#203]
Windows Defender on Win 10 flags Tail 4 Windows as software from unknown vendor (see attached screenshot)

![grafik](https://github.com/tualatin/tailforwindows/assets/53862656/4995731b-87e9-4e36-a897-6ef747afa689)

Could you please add appropriate information so Windows Defender doesn't complain?

Thanks in advance!

**Comment by fakaki** [comment]
I could fix this by myself by allowing this in properties of T4W.exe
![grafik](https://github.com/tualatin/tailforwindows/assets/53862656/d5019a10-6676-456e-b183-70d66b0873d1)

A signed exe would be nice tho but I know that certificates cost money...

**Comment by tualatin** [comment]
The problem is, certificates cost money, this is a free project a nobody want pay 😉
