### ISSUE TITLE
Open not only one log file with command line

### ISSUE THREAD

**Issue by tualatin** [tualatin/tailforwindows#204]
Start a command line. Call the Tail4Window process and add some log file parameters, like:

`T4W c:\temp\xxx.log d:\temp\xyz.log`

Tail4Window should open all log file in separate Tabs.

**Comment by tualatin** [comment]
Merged into master. Fixed and close

**Comment by fakaki** [comment]
Thanks a lot for the bug fix!
Could you please publish a new release build?

**Comment by tualatin** [comment]
@fakaki yes, I will create a new 2.4 release asap. Regards.

**Comment by tualatin** [comment]
@fakaki new release is out.
